### ISSUE TITLE
Sir when will you update PRs??

### ISSUE THREAD

**Issue by manavbansalcoder** [AshuKulu/HacktoberFest2020#214]
Sir please update PRs so that our review period of 14 days get started.....

**Comment by AshuKulu** [comment]
I can understand your concern but i received a huge number of PRs
its not easy to ceck and merge everyones PR
your PR will be valid even if i havenot merge it
it will be only invalid if in case i will mark it invalid
dont worry i will not do that 😊
all the best
leep contributing 👍

**Comment by Anishahaha** [comment]
@AshuKulu hey can you review the opened PRs as half of the month has passed and if you accept them a little late then the maintainer's review period which is 14 days will cross the october month.

**Comment by AshuKulu** [comment]
@Anishahaha Okay, I can understand that
I received a huge number of PRs and it's hectic to merge it one by one
I want to higlight that your PR will be valid even if i haven't merge it, its' only need to pass the reiew period
if the maintainer mark it as invalid then only it's ineligible
It's clearly mentioned in hacktiberfect tnc
Also some rubbish PRs are there that may harm my Repo, if i will mark them invalid they will complain me as i have a mistake
to avoid all such things I'm not doing anything and its not easy to check 200+ PRs one by one
Don't worry Your PR will be valid
I tink you understood
Thank You

**Comment by Vyvy-vi** [comment]
Can the hacktoberfest-accepted label be added, as the PR is not valid for hacktoberfest... 
(Also, if you need help for code sorting, I am currently open and can go through all of them)

**Comment by Vyvy-vi** [comment]
Here are a few of the kinda quality ones ->
#143 #149 #152 #175 #193 #207 #288 #300 #303 
There's a lot of SPAM and a lot of repeated PRs making it long.
I shall post more quality ones if I find them in the PRs.
(*take with a grain of salt, but I kinda hate low quality contributions(cuz ppl are after that free 'tee' and don't care a dime about OpenSource))

**Comment by manavbansalcoder** [comment]
Vyom agreed with you on this . All are here fot tee. I am slso there ashu sir. Will help you if needed
